# Generated by Django 5.2.3 on 2025-07-12 13:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('petId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('raca', models.CharField(max_length=100)),
                ('porte', models.CharField(choices=[('Pequeno', 'Pequeno'), ('Médio', 'Médio'), ('Grande', 'Grande')], max_length=100)),
                ('idade', models.IntegerField()),
                ('descricao', models.CharField(max_length=1000)),
                ('localizacao', models.CharField(max_length=100)),
                ('fotoUrl', models.URLField(max_length=1000)),
                ('status', models.CharField(choices=[('pendente', 'pendente'), ('disponivel', 'disponivel'), ('adotado', 'adotado')], max_length=100)),
                ('ownerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'db_table': 'pets',
            },
        ),
    ]
