# Generated by Django 5.2.3 on 2025-07-12 13:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAdocao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'adoptions_petId',
            },
        ),
        migrations.CreateModel(
            name='AllowAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'db_table': 'adoptions',
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('telefone', models.CharField(max_length=20)),
                ('motivo', models.TextField()),
                ('ambiente', models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento')], max_length=50)),
                ('espacoExterno', models.BooleanField(default=True)),
                ('teveAnimaisAntes', models.BooleanField(default=True)),
                ('ambienteSeguro', models.BooleanField(default=True)),
                ('clientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_enviados', to='users.userprofile')),
            ],
            options={
                'db_table': 'formulario',
            },
        ),
    ]
