# Generated by Django 5.2.3 on 2025-07-12 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adoption', '0001_initial'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='petId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='pets.pet'),
        ),
        migrations.AddField(
            model_name='petadoption',
            name='adoption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption.allowadoption'),
        ),
        migrations.AddField(
            model_name='petadoption',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet'),
        ),
        migrations.AddField(
            model_name='allowadoption',
            name='petId',
            field=models.ManyToManyField(through='adoption.PetAdoption', to='pets.pet'),
        ),
    ]
