# Generated by Django 5.2.3 on 2025-07-12 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petadoption',
            name='adoption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_links', to='adoption.allowadoption'),
        ),
    ]
