# Generated by Django 5.2.3 on 2025-07-25 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_alter_petadoption_adoption'),
        ('pets', '0002_alter_pet_status'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllowAdoption',
            new_name='Adoption',
        ),
    ]
